"""
Build the SIF-Trace working corpus from public safety data.

    python data/build_corpus.py --sir <path to SIR csv> --out data/sif_reports.csv

DATA PROVENANCE - READ THIS BEFORE PRESENTING ANY NUMBER FROM THIS CORPUS
=========================================================================
Actual OIL HSSE data is confidential and is not used anywhere in this project.
Every row carries a `data_source` column recording exactly what is real and what
is constructed:

  narrative           REAL. Verbatim free text written by a safety professional,
                      taken from the OSHA Severe Injury Reports public dataset,
                      filtered to oil & gas NAICS codes.

  sif_label           REAL, and derived INDEPENDENTLY of the narrative text from
                      OSHA's own OIICS `EventTitle`/`NatureTitle` coding. This
                      matters: labels generated by our own rule engine would make
                      the classifier circular and its metrics meaningless.

  location, site,     SYNTHETIC. Assigned deterministically so the corpus has a
  report_type, date   realistic OIL operational geography and reporting mix.
                      These are NOT real OIL sites or real event dates.

Nothing in this corpus is an OIL operational statistic and the application must
never present it as one.

The SIF labelling rule
----------------------
This follows the energy-based Serious Injury & Fatality model used across the
industry (DEKRA; EEI SIF precursor model): an event is SIF-potential when a
HIGH-ENERGY source could plausibly have caused death or permanent impairment,
regardless of the injury that actually resulted.

That is the entire premise of the problem statement - a low-severity outcome can
carry fatal potential - so the label must track the ENERGY, not the outcome.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import re
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "backend"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from sif.config import ASSET_TYPES, OIL_FIELDS  # noqa: E402

csv.field_size_limit(10**9)

# Oil & gas and closely related NAICS prefixes.
OIL_GAS_NAICS = (
    "211",     # oil and gas extraction
    "2131",    # support activities for mining / oil & gas
    "23712",   # oil and gas pipeline construction
    "3241",    # petroleum and coal products manufacturing
    "4247",    # petroleum merchant wholesalers
    "486",     # pipeline transportation
)

# Heavy-industry sectors used ONLY to supplement the low-energy negative class.
#
# Why this is necessary: OSHA SIR is a SEVERE-injury registry, so it structurally
# over-samples high-energy events. The oil & gas slice alone is 76% SIF-potential,
# whereas the problem statement notes that leading operators find genuine fatal
# potential in roughly 20-25% of reports. Training on a 76%-positive corpus would
# produce a model that flags almost everything, which is precisely the triage
# failure this project exists to fix.
#
# So we keep every real oil & gas record and top up the NEGATIVE class with
# low-energy narratives from construction, manufacturing, utilities and transport
# - slips on stairs, tripping over hoses, heat exposure, hand-tool injuries. These
# read plausibly in an E&P setting and are tagged `industrial_analogue` so their
# contribution is always auditable.
INDUSTRIAL_NAICS = ("21", "22", "23", "31", "32", "33", "48", "49")


# --------------------------------------------------------------------------
# Independent SIF label, derived from OSHA's coded event fields
# --------------------------------------------------------------------------

# HIGH-ENERGY event mechanisms - capable of causing death or permanent
# impairment. Matched against OSHA's OIICS EventTitle.
HIGH_ENERGY_EVENT = re.compile(
    r"""
      fall\s+to\s+lower\s+level
    | fall\s+through
    | caught\s+in\s+running\s+equipment
    | caught\s+in\s+or\s+compressed
    | compressed\s+or\s+pinched
    | struck\s+by\s+falling\s+object
    | struck\s+by\s+discharged\s+object
    | struck\s+by\s+dislodged\s+flying\s+object
    | struck\s+by\s+swinging
    | struck\s+by\s+object\s+falling\s+from\s+vehicle
    | struck\s+by\s+powered\s+vehicle
    | pedestrian\s+struck
    | ignition\s+of\s+(?:vapors|vapours|gases|liquids)
    | fire\s+unintended
    | explosion
    | contact\s+with\s+hot\s+objects
    | contact\s+with\s+steam
    | electric
    | exposure\s+to\s+electricity
    | asphyxi
    | oxygen\s+defici
    | inhalation
    | drowning
    | cave-?in
    | collapse
    | engulf
    | roadway\s+incident
    | vehicle
    | rollover
    | non-?roadway
    | caught\s+in\s+or\s+crushed
    | crushed
    | run\s+over
    | entangle
    """,
    re.IGNORECASE | re.VERBOSE,
)

# LOW-ENERGY mechanisms - genuinely serious injuries, but without the energy to
# have plausibly killed the person. These form the negative class.
LOW_ENERGY_EVENT = re.compile(
    r"""
      fall\s+on\s+same\s+level
    | slip.*?without\s+fall
    | exposure\s+to\s+environmental\s+heat
    | exposure\s+to\s+environmental\s+cold
    | overexertion
    | repetitive\s+motion
    | bodily\s+motion
    | injured\s+by\s+slipping\s+or\s+swinging\s+object\s+held
    | rubbed\s+or\s+abraded
    | insect
    | animal
    | bite
    | intentional\s+injury\s+by\s+other\s+person
    | multiple\s+types\s+of\s+overexertion
    """,
    re.IGNORECASE | re.VERBOSE,
)

# Nature-of-injury evidence that the energy really was lethal-capable.
HIGH_ENERGY_NATURE = re.compile(
    r"amputation|crush|internal\s+injur|intracranial|spinal|asphyxi|electrocut"
    r"|third\s+degree|traumatic|avulsion|bone\s+loss|multiple\s+traumatic",
    re.IGNORECASE,
)


def derive_sif_label(event_title: str, nature_title: str, amputation: str) -> tuple[int, str]:
    """
    Return (label, reason) using ONLY OSHA's coded fields - never the narrative.

    1 = SIF-potential, 0 = not SIF-potential.
    """
    event = (event_title or "").strip()
    nature = (nature_title or "").strip()

    if LOW_ENERGY_EVENT.search(event):
        return 0, f"low-energy mechanism ({event[:48]})"

    if HIGH_ENERGY_EVENT.search(event):
        return 1, f"high-energy mechanism ({event[:48]})"

    # Fall back to injury nature: an amputation or crush injury is prima facie
    # evidence that lethal-capable energy was released.
    if HIGH_ENERGY_NATURE.search(nature):
        return 1, f"lethal-capable energy implied by injury nature ({nature[:40]})"

    try:
        if float(amputation or 0) > 0:
            return 1, "amputation recorded"
    except (TypeError, ValueError):
        pass

    return 0, f"no high-energy mechanism identified ({event[:40] or 'unspecified'})"


# --------------------------------------------------------------------------
# Synthetic operational overlay (deterministic, reproducible)
# --------------------------------------------------------------------------


def _h(seed: str, salt: str) -> int:
    return int(hashlib.sha256(f"{salt}:{seed}".encode()).hexdigest()[:12], 16)


# Work content -> asset type. Narratives are routed to the kind of installation
# where that work actually happens.
#
# This is what makes the site-density ranking mean anything. Assigning locations
# by pure hash would give every site the corpus-average SIF rate, and the site
# ranking - a core deliverable - would rank nothing but sampling noise. Real
# asset bases are not uniform: a drilling rig carries far more line-of-fire and
# working-at-height exposure than a pump station, so density genuinely varies.
ACTIVITY_ASSET_AFFINITY: list[tuple[re.Pattern, list[str]]] = [
    (re.compile(r"derrick|drill|rotary|tong|mud\s+pump|casing|blow.?out|rig\s+floor", re.I),
     ["Drilling Rig", "Drilling Rig", "Well Head"]),
    (re.compile(r"work.?over|wireline|coiled\s+tubing|swab|pulling\s+(?:rod|tubing)|well\s+servic", re.I),
     ["Workover Rig", "Workover Rig", "Well Head"]),
    (re.compile(r"pipeline|flow.?line|pigging|right.of.way|trench|excavat", re.I),
     ["Pipeline Section", "Pipeline Section", "Group Gathering Station"]),
    (re.compile(r"compressor|gas\s+plant|lpg|propane|butane|turbine", re.I),
     ["Gas Compressor Station", "LPG Plant"]),
    (re.compile(r"separator|tank|vessel|storage|crude|manifold|gathering", re.I),
     ["Oil Collecting Station", "Group Gathering Station", "Crude Oil Pump Station"]),
    (re.compile(r"weld|grind|lathe|machine\s+shop|fabricat|workshop", re.I),
     ["Central Workshop", "Central Workshop", "Oil Collecting Station"]),
    (re.compile(r"forklift|truck|trailer|vehicle|driv|transport|load(?:ing)?\s+dock", re.I),
     ["Pipeline Section", "Central Workshop", "Crude Oil Pump Station"]),
    (re.compile(r"pump|valve|motor|electrical|panel|switchgear", re.I),
     ["Crude Oil Pump Station", "Oil Collecting Station"]),
]

# Which assets each field operates. Fields specialise, exactly as OIL's do:
# some areas are drilling-intensive, others are production-gathering hubs.
FIELD_ASSET_PROFILE: dict[str, list[str]] = {
    "Baghjan": ["Drilling Rig", "Well Head", "Workover Rig"],
    "Dikom": ["Drilling Rig", "Well Head"],
    "Kusijan": ["Drilling Rig", "Workover Rig"],
    "Jaisalmer - Tanot": ["Drilling Rig", "Well Head", "Gas Compressor Station"],
    "Jaisalmer - Dandewala": ["Gas Compressor Station", "Well Head"],
    "Moran": ["Workover Rig", "Well Head", "Oil Collecting Station"],
    "Jorajan": ["Workover Rig", "Oil Collecting Station"],
    "Hapjan": ["Workover Rig", "Group Gathering Station"],
    "Duliajan": ["Central Workshop", "Oil Collecting Station", "Crude Oil Pump Station"],
    "Naharkatiya": ["Oil Collecting Station", "Group Gathering Station", "Well Head"],
    "Shalmari": ["Group Gathering Station", "Oil Collecting Station"],
    "Barekuri": ["Group Gathering Station", "Well Head"],
    "Makum": ["Pipeline Section", "Crude Oil Pump Station"],
    "Tengakhat": ["Pipeline Section", "Group Gathering Station"],
    "Chabua": ["Pipeline Section", "Crude Oil Pump Station"],
    "Digboi": ["LPG Plant", "Crude Oil Pump Station", "Central Workshop"],
    "Kumchai": ["Well Head", "Oil Collecting Station"],
    "KG Basin - Kakinada": ["Gas Compressor Station", "Pipeline Section", "Well Head"],
}

# Relative reporting volume per field, so the corpus is not uniformly spread.
FIELD_VOLUME: dict[str, int] = {
    "Duliajan": 10, "Naharkatiya": 8, "Moran": 8, "Jorajan": 7, "Baghjan": 7,
    "Hapjan": 6, "Shalmari": 6, "Barekuri": 5, "Dikom": 5, "Kusijan": 5,
    "Makum": 4, "Tengakhat": 4, "Chabua": 4, "Digboi": 4, "Kumchai": 3,
    "Jaisalmer - Tanot": 3, "Jaisalmer - Dandewala": 2, "KG Basin - Kakinada": 3,
}

_ASSET_FIELDS: dict[str, list[str]] = {}
for _f, _assets in FIELD_ASSET_PROFILE.items():
    for _a in _assets:
        _ASSET_FIELDS.setdefault(_a, []).extend([_f] * FIELD_VOLUME.get(_f, 3))


def assign_site(report_id: str, narrative: str = "") -> tuple[str, str]:
    """
    Assign an OIL field and asset consistent with the work the narrative describes.

    Deterministic in `report_id`, so the corpus is byte-reproducible.
    """
    asset = None
    for rx, assets in ACTIVITY_ASSET_AFFINITY:
        if rx.search(narrative):
            asset = assets[_h(report_id, "asset") % len(assets)]
            break
    if asset is None:
        asset = ASSET_TYPES[_h(report_id, "asset2") % len(ASSET_TYPES)]

    pool = _ASSET_FIELDS.get(asset)
    if not pool:
        pool = [f for f, w in FIELD_VOLUME.items() for _ in range(w)]
    field_name = pool[_h(report_id, "field") % len(pool)]
    return field_name, asset


def assign_report_type(report_id: str, is_sif: int) -> str:
    """
    Every OSHA Severe Injury Report record is an injury that already happened,
    so the only truthful type for a real record is "Incident".

    Typing them "Unsafe Act" or "Near Miss" produced narratives that contradicted
    their own label - an unsafe-condition observation ending in surgery. The
    UA/UC/Near-Miss layer is generated separately in synthetic_observations.py,
    where the text genuinely describes a pre-injury observation.
    """
    return "Incident"


def assign_date(report_id: str, event_date: str) -> str:
    """Keep the real month/day shape but shift into a recent 24-month window."""
    base = date.today().replace(day=1) - timedelta(days=730)
    return (base + timedelta(days=_h(report_id, "date") % 730)).isoformat()


def assign_status(report_id: str) -> str:
    r = _h(report_id, "status") % 100
    if r < 58:
        return "Pending Review"
    if r < 86:
        return "Under Review"
    return "Reviewed"


# --------------------------------------------------------------------------
# Build
# --------------------------------------------------------------------------

OUTPUT_COLUMNS = [
    "report_id",
    "date",
    "location",
    "asset",
    "report_type",
    "narrative",
    "sif_label",
    "sif_label_reason",
    "source_event_code",
    "source_nature",
    "data_source",
    "narrative_provenance",
    "context_provenance",
    "sector_provenance",
]


def build(
    sir_path: Path,
    out_path: Path,
    limit: int | None = None,
    target_sif_rate: float = 0.25,
    n_observations: int = 1200,
) -> dict:
    oil_rows: list[dict] = []
    industrial_negatives: list[dict] = []
    seen_narratives: set[str] = set()
    skipped_short = 0
    skipped_dupe = 0

    with sir_path.open(newline="", encoding="utf-8", errors="replace") as fh:
        for rec in csv.DictReader(fh):
            naics = (rec.get("Primary NAICS") or "").strip()
            is_oil = naics.startswith(OIL_GAS_NAICS)
            is_industrial = naics.startswith(INDUSTRIAL_NAICS)
            if not (is_oil or is_industrial):
                continue

            narrative = re.sub(r"\s+", " ", (rec.get("Final Narrative") or "").strip())
            if len(narrative) < 60:
                skipped_short += 1
                continue

            key = narrative.lower()[:200]
            if key in seen_narratives:
                skipped_dupe += 1
                continue
            seen_narratives.add(key)

            label, reason = derive_sif_label(
                rec.get("EventTitle", ""),
                rec.get("NatureTitle", ""),
                rec.get("Amputation", ""),
            )

            # Non-oil records are admitted ONLY as low-energy negatives. Pulling
            # in their positives too would swamp the corpus with non-E&P
            # high-energy narratives and dilute the domain signal.
            if not is_oil and label == 1:
                continue

            rid_src = (rec.get("ID") or "").strip() or key
            report_id = f"OIL-{_h(rid_src, 'rid') % 900000 + 100000}"
            location, asset = assign_site(report_id, narrative)

            row = {
                "report_id": report_id,
                "date": assign_date(report_id, rec.get("EventDate", "")),
                "location": location,
                "asset": asset,
                "report_type": assign_report_type(report_id, label),
                "narrative": narrative,
                "sif_label": label,
                "sif_label_reason": reason,
                "source_event_code": (rec.get("EventTitle") or "").strip(),
                "source_nature": (rec.get("NatureTitle") or "").strip(),
                "data_source": "OSHA Severe Injury Reports (public)",
                "narrative_provenance": "real",
                "context_provenance": "synthetic",
                "sector_provenance": "oil_gas" if is_oil else "industrial_analogue",
            }
            (oil_rows if is_oil else industrial_negatives).append(row)

    # Keep every real oil & gas record, then top up negatives to hit the target
    # SIF rate. Selection is hash-ordered, so the corpus is byte-reproducible.
    n_sif = sum(r["sif_label"] for r in oil_rows)
    n_neg_have = len(oil_rows) - n_sif
    total_wanted = int(round(n_sif / target_sif_rate)) if target_sif_rate > 0 else len(oil_rows)
    need = max(0, total_wanted - len(oil_rows))

    industrial_negatives.sort(key=lambda r: _h(r["report_id"], "pick"))
    rows = oil_rows + industrial_negatives[:need]

    # Observation layer: real records cannot supply UA/UC/near-miss text,
    # because every one of them is an injury. Generated separately and tagged.
    if n_observations:
        from synthetic_observations import generate

        for i, obs in enumerate(generate(n_observations, OIL_FIELDS, ASSET_TYPES)):
            rid = f"OIL-{_h(obs['seed'], 'rid') % 900000 + 100000}"
            location, asset = assign_site(rid, obs["narrative"])
            rows.append(
                {
                    "report_id": rid,
                    "date": assign_date(rid, ""),
                    "location": location,
                    "asset": asset,
                    "report_type": obs["report_type"],
                    "narrative": obs["narrative"],
                    "sif_label": obs["sif_label"],
                    "sif_label_reason": obs["sif_label_reason"],
                    "source_event_code": "",
                    "source_nature": "",
                    "data_source": "Synthetic OIL-style observation (generated)",
                    "narrative_provenance": "synthetic",
                    "context_provenance": "synthetic",
                    "sector_provenance": "oil_gas_observation",
                }
            )

    # Stable ordering, then write.
    rows.sort(key=lambda r: (r["date"], r["report_id"]))
    if limit:
        rows = rows[:limit]
    for i, r in enumerate(rows, 1):
        r["report_id"] = f"{r['report_id']}-{i:04d}"

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=OUTPUT_COLUMNS)
        w.writeheader()
        w.writerows(rows)

    n_sif_final = sum(r["sif_label"] for r in rows)
    n_oil = sum(r["sector_provenance"] == "oil_gas" for r in rows)
    n_obs = sum(r["narrative_provenance"] == "synthetic" for r in rows)
    return {
        "rows": len(rows),
        "sif": n_sif_final,
        "non_sif": len(rows) - n_sif_final,
        "sif_rate": round(n_sif_final / len(rows), 4) if rows else 0.0,
        "oil_gas_rows": n_oil,
        "analogue_rows": len(rows) - n_oil,
        "oil_negatives_kept": n_neg_have,
        "observations": n_obs,
        "skipped_short": skipped_short,
        "skipped_dupe": skipped_dupe,
        "locations": len({r["location"] for r in rows}),
        "out": str(out_path),
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--sir", required=True, type=Path, help="OSHA SIR CSV path")
    ap.add_argument("--out", default=Path("data/sif_reports.csv"), type=Path)
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument(
        "--observations",
        type=int,
        default=1200,
        help="synthetic OIL-style UA/UC/near-miss observations to append",
    )
    ap.add_argument(
        "--sif-rate",
        type=float,
        default=0.25,
        help="target share of SIF-potential rows (industry benchmark 0.20-0.25)",
    )
    args = ap.parse_args()

    if not args.sir.exists():
        raise SystemExit(f"SIR file not found: {args.sir}")

    stats = build(args.sir, args.out, args.limit, args.sif_rate, args.observations)
    print("SIF-Trace corpus built")
    for k, v in stats.items():
        print(f"  {k:<14} {v}")


if __name__ == "__main__":
    main()
